#pragma once
void getcnip();
void gfwlist2pac();
void get_cn_domains();
void generate_user_dot_rule();
void generate_ss_cnip();
void generate_ss_white();
void generate_ss_white_r();
void generate_local_cnip();